- name: repositorio default
  deb822_repository:
    name: default
    types: deb
    uris: http://deb.debian.org/debian
    suites: trixie
    components:
      - main
      - contrib
      - non-free
      - non-free-firmware
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

- name: repositorio security
  deb822_repository:
    types: deb
    name: security
    uris: https://security.debian.org/debian-security
    suites: trixie-security
    components:
      - main
      - contrib
      - non-free
      - non-free-firmware
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

- name: repositorio updates
  deb822_repository:
    types: deb
    name: updates
    uris: http://deb.debian.org/debian
    suites: trixie-updates
    components:
      - main
      - contrib
      - non-free
      - non-free-firmware
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

- name: repositorio backports
  deb822_repository:
    types: deb
    name: backports
    uris: http://deb.debian.org/debian
    suites: trixie-backports
    components:
      - main
      - contrib
      - non-free
      - non-free-firmware
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

- name: limpa sources.list
  copy:
    content: ""
    dest: /etc/apt/sources.list

- name: limpa reposit贸rio default antigo
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/default.list
    state: absent

- name: limpa reposit贸rio security antigo
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/security.list
    state: absent

- name: limpa reposit贸rio updates antigo
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/updates.list
    state: absent

- name: limpa reposit贸rio backports antigo
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/backports.list
    state: absent

- name: pacotes basicos
  apt:
    update_cache: yes
    pkg:
      - aptitude
      - bmon
      - colordiff
      - debian-keyring
      - dos2unix
      - emacs
      - ethtool
      - htop
      - iftop
      - iotop
      - ipcalc
      - lsb-release
      - lshw
      - lsscsi
      - ltrace
      - members
      - ncdu
      - nethogs
      - nmap
      - pssh
      - pwgen
      - rasdaemon
      - rsync
      - rsyslog-gnutls
      - screen
      - smartmontools
      - s-nail
      - strace
      - subnetcalc
      - sysstat
      - tcpdump
      - tmux
      - tree
      - unattended-upgrades
      - unicode
      - vim
      - wakeonlan

- name: retira 127.0.1.1 do hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1.*'
    state: absent

- name: adiciona IP correto ao hosts
  lineinfile:
    path: /etc/hosts
    insertafter: '^127\.0\.0\.1.*'
    regexp: ".*{{ ansible_facts['fqdn'] }}.*{{ ansible_facts['hostname'] }}"
    line: "{{ ansible_facts['default_ipv4']['address']}} {{ ansible_facts['fqdn'] }} {{ ansible_facts['hostname'] }}"
    state: present

- name: gambi nfs
  lineinfile:
    path: /etc/hosts
    insertafter: '^127\.0\.0\.1.*'
    line: "200.144.254.25 moros.ad.ime.usp.br moros"
    state: present

- name: ntp
  lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: '^NTP='
    line: NTP=ntp.usp.br
  notify: reinicia timesyncd

- name: pam mkhomedir
  lineinfile:
    path: /etc/pam.d/common-session
    line: session optional pam_mkhomedir.so

- name: chaves de ssh
  authorized_key:
    user: root
    key: "{{ item }}"
  with_list:
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1fsiDkr9qqxTSYJm3MsekJTBw7noFQ6d50zniKLeoLa0C66hfB2NNncmzM64STj69SdvF9DhmZ1q9yuS1m/QApy+/XWLZrC7FkDn+UrrcXdqo0BGjhZZIIA3dyJ24NIcmJs7gUGJ4YJfHu+lV+Ch9E5mqKuYu3WhG+XW9hbthMuDBG01JNSJJYRz2SY8vKZa9WStJA+KUYeUZ9tOoThr3QtxuoLUhdKgnEPFRADOjL+CHJ6Uit2erbVOtu+LEIztYCg8t5Bmg+UqcwWQrtdYxFI40g543QedICEZK05SxigdL/f6vBqBfd1epQ26i9YeRYOy6dHO2sg26ZaWYDIIl"
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIqjxCvQcwdgzTcugkyOXrSLJIRHZT92LEFz9vcfIooPlUzx/2EJWadSmcYFf9tEU2234R3QIQcySkq8934HHvIeJKerlk/XFBcGEV9RQlH78AHmThxitSxmR4XqWekodjPZV2ZrVf7k9F2ADQTh0Cv+gV6KOAkKdTda9ic9af/t6J6GnlPPS+elzTa0LhTo6zBmmO/mSVkAnuj3aTq67P89mvvBKgu/CJD6WDi+oJT6phrIjKXBLVx7ry4O3/KBhfOaVooRp/hz8JxGTLm+0fH26jwTicsdOTkhu0n6actL4RNAUyZF6WP8bFnMPaEpCaZMLyCOv7+1XMkcuqRiYHHjRUg+O38nRN3Sk0Wv7gZ96sbL0FWYz5LZoEEjSj+6V6jmwjmrxmrPeokpb/d8kSlfbhqir6l00d6F/3xiD78wfMm0l11ZUXvht4ZW5Bv0vPhCWbCUx9uKotvHThNDLkOadYB8/I6HHNI16a+Qsoruel69owEnLXWkY4RPn6kuHq2ctF5opqQ+AuaP4zjaOw8GAVNgEmloIJ+ZVt9LK5eDkU6ulQ1eWt40luECfInUXOm95RGCOinXBhDaV1mT09+9tRBDuuINAj6x/3lFJMoFfujCUbRDtJHHY6WD7L8SmgWEaJ71BYzOm0F1CgZchhZa/Jww8MWdkroTPoxJm9hw=="
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG3oEW3u5gpiFrqSqEPWemAcVB8jisX4kQGxBrapXDV3"
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOlvwfNGpLDJ3/QQM8ojhjUyBCbdU2jTILimePUWPrSq"

- name: coloca o 20auto-upgrades no apt.conf.d
  ansible.builtin.copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '644'
