# Miniconda
- name: chave do repositório do miniconda
  ansible.builtin.get_url:
    url: '{{ conda_keyfile_url }}'
    dest: '{{ apt_keyring_path }}/{{ conda_keyring_file }}'
    checksum: '{{ conda_keyfile_checksum }}'

- name: arquivo do repositório do miniconda
  ansible.builtin.apt_repository:
    repo: 'deb [ signed-by={{ apt_keyring_path }}/{{ conda_keyring_file}} ] https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main'
    filename: conda

- name: instala miniconda
  ansible.builtin.apt:
    update_cache: yes
    state: latest
    pkg:
      - conda

- name: coloca miniconda no PATH
  ansible.builtin.copy:
    content: export PATH=${PATH}:/opt/conda/bin/
    dest: /etc/profile.d/conda_path.sh

- name: coloca source do PATH do conda no bashrc
  ansible.builtin.lineinfile:
    path: /etc/bash.bashrc
    line: source /etc/profile.d/conda_path.sh

# Apptainer
- name: install apptainer
  apt:
    deb: https://github.com/apptainer/apptainer/releases/download/v1.3.0/apptainer_1.3.0_amd64.deb

- name: garante que existe o /opt/apptainer
  ansible.builtin.file:
    path: /opt/apptainer
    state: directory
    owner: root
    group: root
    mode: '755'

- name: copia o script rstudio_apptainer.sh
  ansible.builtin.copy:
    src: rstudio_apptainer.sh
    dest: /usr/local/bin/rstudio_apptainer.sh
    owner: root
    group: root
    mode: '755'

- name: copia o script rstudio com orientações sobre apptainer
  ansible.builtin.copy:
    src: rstudio
    dest: /usr/local/bin/rstudio
    owner: root
    group: root
    mode: '755'

- name: copia o script R com orientações sobre apptainer
  ansible.builtin.copy:
    src: R
    dest: /usr/local/bin/R
    owner: root
    group: root
    mode: '755'

- name: copia os icones do rstudio e do R nos locais apropriados
  ansible.builtin.copy:
    src: icons
    dest: /usr/share/
    owner: root
    group: root
    directory_mode: '755'
    mode: '644'
    recurse: yes

- name: copia os .desktop de R e Rstudio para redirecionar à página da wiki
  ansible.builtin.copy:
    src: applications
    dest: /usr/share/
    owner: root
    group: root
    directory_mode: '755'
    mode: '644'
    recurse: yes
    
# Resto
- name: pacotes dev
  apt:
    update_cache: yes
    pkg:
      - amqp-tools
      - build-essential
      - curl
      - fish
      - gap
      - gdb
      - gfortran
      - git
      - jq
      - libfontconfig1-dev
      - libfribidi-dev
      - libgdal-dev
      - libgsl-dev
      - libharfbuzz-dev
      - libpnetcdf-dev
      - libnode-dev
      - libproj-dev
      - libudunits2-dev
      - libx11-dev
      - nasm
      - plink1.9
      - pnetcdf-bin
      - python3-pip
      - python3-pygments
      - texlive-full
      - octave
      - zbar-tools
      - zstd

